### ISSUE TITLE
The specified module could not be found (omniExampleSchema.dll)

### ISSUE THREAD

**Issue by ThaiLe-gt** [NVIDIA-Omniverse/usd-plugin-samples#16]
I've tried building the example schema and loading it into Omniverse through the example extension, but I always get an error that omniExampleSchema.dll cannot be found in the folder as the log below.

Please help me to solve it!

My test environment:
- Window 11
- KIT 106.3 and Composer 2023.2.5
- MSVC v142 - VS 2019 C++ x64/x86

`2024-11-07 09:49:05  [Error] [omni.ext.plugin] Could not load the dynamic library from d:/works/ominverse/dev/openusd/dime/schema/usd-plugin-samples/src/test/omni.example.schema/OmniExampleSchema/lib/omniExampleSchema.dll. Error: The specified module could not be found.
2024-11-07 09:49:05  [Error] [omni.ext.plugin]  (note that this may be caused by a dependent library)
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer] Failed to import python module OmniExampleSchema. Error: DLL load failed while importing _omniExampleSchema: The specified module could not be found.. Traceback:
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer] Traceback (most recent call last):
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "c:\users/thai le/appdata/local/ov/pkg/kit-106.3.0/kernel/py\omni\ext\_impl\custom_importer.py", line 76, in import_module
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]     return importlib.import_module(name)
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "c:\users\thai le\appdata\local\ov\pkg\kit-106.3.0\python\lib\importlib\__init__.py", line 126, in import_module
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]     return _bootstrap._gcd_import(name[level:], package, level)
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "d:/works/ominverse/dev/openusd/dime/schema/usd-plugin-samples/src/test/omni.example.schema/OmniExampleSchema/__init__.py", line 8, in <module>
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]     Tf.PreparePythonModule()
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "c:/users/thai le/appdata/local/ov/pkg/kit-106.3.0/exts/omni.usd.libs-1.0.1+0d669cdf.wx64.r.cp310/pxr/Tf/__init__.py", line 89, in PreparePythonModule
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]     module = importlib.import_module(
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "c:\users\thai le\appdata\local\ov\pkg\kit-106.3.0\python\lib\importlib\__init__.py", line 126, in import_module
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]     return _bootstrap._gcd_import(name[level:], package, level)
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 571, in module_from_spec
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap_external>", line 1176, in create_module
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer] ImportError: DLL load failed while importing _omniExampleSchema: The specified module could not be found.
2024-11-07 09:49:05  [Error] [omni.ext._impl.custom_importer] 
2024-11-07 09:49:05  [Error] [carb.scripting-python.plugin] Exception: Extension python module: 'OmniExampleSchema' in 'd:\works\ominverse\dev\openusd\dime\schema\usd-plugin-samples\src\test\omni.example.schema' failed to load.
2024-11-07 09:49:05  [Error] [carb.scripting-python.plugin] 
2024-11-07 09:49:05  [Error] [carb.scripting-python.plugin] At:
2024-11-07 09:49:05  [Error] [carb.scripting-python.plugin]   c:\users/thai le/appdata/local/ov/pkg/kit-106.3.0/kernel/py\omni\ext\_impl\_internal.py(213): startup
2024-11-07 09:49:05  [Error] [carb.scripting-python.plugin]   c:\users/thai le/appdata/local/ov/pkg/kit-106.3.0/kernel/py\omni\ext\_impl\_internal.py(328): startup_extension
2024-11-07 09:49:05  [Error] [carb.scripting-python.plugin]   PythonExtension.cpp::startup()(2): <module>
2024-11-07 09:49:05  [Error] [carb.scripting-python.plugin] 
2024-11-07 09:49:05  [Error] [omni.ext.plugin] [ext: omni.example.schema-1.0.0] Failed to startup python extension.
`

**Comment by ThaiLe-gt** [comment]
I resolved the issue by building the schema based on the new USD plugin in the **kit106_update** branch. I’ll go ahead and close this issue.
